const char *const rbom_ddl=
   "database rbom {\n"
   "    data file \"rbom.d01\" contains ritem;\n"
   "    data file \"rbom.d02\" contains rbill;\n"
   "    key file  \"rbom.k01\" contains rid_code;\n"
   "    key file  \"rbom.k02\" contains rbom, rwhere_used;\n"
   "\n"
   "    record ritem {\n"
   "        unique key char rid_code[16];\n"
   "        char    rdescription[58];\n"
   "        double  rcost;\n"
   "        int32_t rcomponent_count;\n"
   "    }\n"
   "    record rbill {\n"
   "        char    rparent[16];\n"
   "        char    rcomponent[16];\n"
   "        int32_t rsequence;\n"
   "        double  rquantity;\n"
   "        int32_t rlevel;\n"
   "\n"
   "        compound key rbom {\n"
   "            rparent;\n"
   "            rsequence;\n"
   "        }\n"
   "        compound key rwhere_used {\n"
   "            rcomponent;\n"
   "            rsequence;\n"
   "        }\n"
   "    }\n"
   "}\n";

