OPEN bookshop EXCLUSIVE;
INITIALIZE bookshop;
.m
.m **** Importing data into the BOOKSHOP database
.m
.m Importing data into acctmgr table...
import into acctmgr from file "acctmgrs.txt";
.m Importing data into patron table...
import into patron from file "patrons.txt";
.m Importing data into author table...
import into author from file "authors.txt";
.m Importing data into book table...
import into book from file "books.txt";
.m Importing data into related_name table...
import into related_name from file "names.txt";
.m Importing data into genres table...
import into genres from file "genres.txt";
.m Importing data into subjects table...
import into subjects from file "subjects.txt";
.m Importing data into genres_books table...
import into genres_books from file "bookgens.txt";
.m Importing data into subjects_books table...
import into subjects_books from file "booksubs.txt";
.m Importing data into note table...
import into note from file "bnotes.txt";
import into note from file "pnotes.txt";
.m Importing data into note_line table...
import into note_line from file "bnotelines.txt";
import into note_line from file "pnotelines.txt";
.m Importing data into sale table...
import into sale from file "sales.txt";
commit;
.m
.m **** BOOKSHOP database import complete
.m
