static const char *const author_txt=
   "1:1,\"Martin, James\"\n"
   "1:2,\"Myers, G.\"\n"
   "1:3,\"Teorey T. & Fry, J.\"\n"
   "1:4,\"Flavin, M.\"\n"
   "1:5,\"Ullman, J.\"\n"
   "1:6,\"Wiederhold, G.\"\n"
   "1:7,\"Auerbach Ed. staff\"\n"
   "1:8,\"Knuth, D.\"\n"
   "1:9,\"Lewis, Rosenkrantz, Stearns\"\n"
   "1:10,\"Gries, D.\"\n"
   "1:11,\"Aho, Hopcroft, Ullman\"\n"
   "1:12,\"Dahl, Dijkstra, Hoare\"\n"
   "1:13,\"Coffman & Denning\"\n"
   "1:14,\"Comer, D.\"\n"
   "1:15,\"Holsapple, C.\"\n"
   "1:16,\"Kruglinski, D.\"\n"
   "1:17,\"Sibley, E.\"\n"
   ;
