static const char *const key_word_txt=
   "0:2,\"4GL\"\n"
   "0:3,\"languages\"\n"
   "0:4,\"reliability\"\n"
   "0:5,\"debugging\"\n"
   "0:6,\"testing\"\n"
   "0:7,\"database design\"\n"
   "0:8,\"database technology\"\n"
   "0:9,\"database administration\"\n"
   "0:10,\"algorithms\"\n"
   "0:11,\"data structures\"\n"
   "0:12,\"random numbers\"\n"
   "0:13,\"arithmetic\"\n"
   "0:14,\"sorting\"\n"
   "0:15,\"searching\"\n"
   "0:16,\"compilers\"\n"
   "0:17,\"parsing\"\n"
   "0:18,\"computational models\"\n"
   "0:19,\"structured programming\"\n"
   "0:20,\"verification\"\n"
   "0:21,\"operating systems\"\n"
   "0:22,\"concurrency\"\n"
   "0:23,\"scheduling\"\n"
   "0:24,\"memory management\"\n"
   "0:25,\"B-tree\"\n"
   "0:26,\"database models\"\n"
   "0:27,\"database\"\n"
   "0:28,\"network model\"\n"
   ;
