static const char *const text_txt=
   "1:18,\"General principles relating to 4GLs are described.\"\n"
   "1:19,\"Example 4GLs are described.\"\n"
   "1:20,\"Factors affecting the reliability of software and techniques\"\n"
   "1:20,\"for producing reliable software are described.  Standard software\"\n"
   "1:20,\"development lifecycle methods form the foundation for building\"\n"
   "1:20,\"software with a minimum of errors.\"\n"
   "1:21,\"A thorough treatment of all aspects of database design.\"\n"
   "1:22,\"Information modeling is a form of systems analysis which is\"\n"
   "1:22,\"particularly important for the database designer.  Key semantic\"\n"
   "1:22,\"concepts of information modeling, decision rules, and heuristics\"\n"
   "1:22,\"and modeling strategies to assist in formulation of a systematic\"\n"
   "1:22,\"approach to model development are presented.\"\n"
   "1:23,\"An excellent presentation of current technology used in the\"\n"
   "1:23,\"implementation of database management systems.  Topics discussed\"\n"
   "1:23,\"include: physical data organization, database models, query\"\n"
   "1:23,\"languages and optimization, design techniques, security, \"\n"
   "1:23,\"concurrency, and distributed databases.\"\n"
   "1:24,\"A thorough treatment of database management systems technology. \"\n"
   "1:24,\"Covers a multiplicity of file organization techniques which can\"\n"
   "1:24,\"be used by a DBMS.  Also describes major database structures and\"\n"
   "1:24,\"query language concepts.  Good information is provided on \"\n"
   "1:24,\"database concurrency and security.\"\n"
   "1:25,\"Provides a wealth of information about managment and planning\"\n"
   "1:25,\"issues, database administration, and database design.  As its\"\n"
   "1:25,\"name indicates this is a very practical book.\"\n"
   "1:26,\"This classic text presents basic computer science concepts and\"\n"
   "1:26,\"algorithms which implement standard data structures such as\"\n"
   "1:26,\"stacks, queues, linked lists, and trees.\"\n"
   "1:27,\"Classic text which includes everything you need to know about\"\n"
   "1:27,\"generating good random numbers.  Algorithms for performing\"\n"
   "1:27,\"computations on arbitrarily large numbers, floating point,\"\n"
   "1:27,\"polynomials, etc. are also presented.\"\n"
   "1:28,\"Classic text presenting the major algorithms for performing both\"\n"
   "1:28,\"internal and external sorts and searches.\"\n"
   "1:29,\"A very readable text presenting the fundamentals of compiler\"\n"
   "1:29,\"construction.\"\n"
   "1:30,\"Presents the basic techniques relating to most of the aspects\"\n"
   "1:30,\"of compiler construction.  Does not skimp on his presentation\"\n"
   "1:30,\"of techniques for symbol table management, memory usage, and\"\n"
   "1:30,\"code generation.  Other texts overemphasize parsing (the easy\"\n"
   "1:30,\"part).\"\n"
   "1:31,\"A classic text which describes the process of algorithm design\"\n"
   "1:31,\"and analysis and then presents algorithms for many of the\"\n"
   "1:31,\"standard computer science techniques.\"\n"
   "1:32,\"A collection of essays from three of the great pioneers of\"\n"
   "1:32,\"computer science.\"\n"
   "1:33,\"A presentation of a program development technique based upon\"\n"
   "1:33,\"the application of methods of proving programs correct. \"\n"
   "1:34,\"Formal analytical methods are used to present standard operating\"\n"
   "1:34,\"systems technology including: concurrency control, scheduling,\"\n"
   "1:34,\"and demand paging.\"\n"
   "1:35,\"An excellent survey article about the B-tree indexing method.\"\n"
   "1:36,\"An overview of the standard data models is presented by an\"\n"
   "1:36,\"MDBS consultant.\"\n"
   "1:37,\"An excellent guide to a variety of database management systems\"\n"
   "1:37,\"available on microcomputers.\"\n"
   "1:38,\"An article which describes the benefits of the network database\"\n"
   "1:38,\"model featurigng db_VISTA. \"\n"
   "1:39,\"An excellent survey of the majors issues in database technology\"\n"
   "1:39,\"in 1976.  It's interesting that not really very much has changed\"\n"
   "1:39,\"since then except that now there are production relational\"\n"
   "1:39,\"systems available.  Good reading for those who have no database\"\n"
   "1:39,\"background.\"\n"
   "1:40,\"One of the definitive texts on all aspects of database\"\n"
   "1:40,\"management systems.\"\n"
   ;
