static const char *const bom_ddl=
   "database bom {\n"
   "    data file \"bom.d01\" contains item;\n"
   "    data file \"bom.d02\" contains bill;\n"
   "    key file  \"bom.k01\" contains id_code;\n"
   "\n"
   "    record item {\n"
   "        unique key char id_code[16];\n"
   "        char   description[58];\n"
   "        double cost;\n"
   "    }\n"
   "    record bill {\n"
   "        double  quantity;\n"
   "        int32_t level;\n"
   "    }\n"
   "\n"
   "    set bom {\n"
   "        order last;\n"
   "        owner item;\n"
   "        member bill;\n"
   "    }\n"
   "    set where_used {\n"
   "        order last;\n"
   "        owner item;\n"
   "        member bill;\n"
   "    }\n"
   "}\n";
