# Auto generated please do not edit this file

#include $(RDM_HOME)$/sysmake$/$(KMAKESYS).mak
CC_INCL = $I../include 

#include $(RDM_HOME)$/kheader.mak

all GettingStarted:
    krun examples          kmake -rf kmake.mak
    krun tutorials          kmake -rf kmake.mak

embedfiles test clean cleanall clean_all:
    krun examples          kmake -rf kmake.mak $@
    krun tutorials          kmake -rf kmake.mak $@


